export default [
    {
        userId: 1,
        userName: 'Jaylon Schleifer',
        userIcon: '',
        position: 'developer',
        email: 'jaylon.schleifer@gmail.com',
        phone: '+35795111111',
        skype: '@jaylon-schleifer',
        link: 'https://www.linkedin.com/in/jaylon-schleifer/',
        questionnaire: [
            {
                questId: 1,
                questName: 'questionnaire',
                startDate: '5.5.2022',
                endDate: '',
                status: 'progress',
                isFinish: false,
                steps: [],
            },
            {
                questId: 2,
                questName: 'instruction',
                startDate: '5.5.2022',
                endDate: '6.5.2022',
                status: 'done',
                isFinish: true,
                steps: [],
            },
            {
                questId: 3,
                questName: 'contact information',
                startDate: '7.5.2022',
                endDate: '',
                status: 'open',
                isFinish: false,
                steps: [],
            },
        ],
    },
    {
        userId: 2,
        userName: 'Ahmad Stanton',
        userIcon: '',
        position: 'developer',
        email: 'ahmad.stanton@gmail.com',
        phone: '+35795111111',
        skype: '@ahmad-stanton',
        link: 'https://www.linkedin.com/in/ahmad-stanton/',
        questionnaire: [
            {
                questId: 1,
                questName: 'questionnaire',
                startDate: '6.5.2022',
                endDate: '',
                status: 'open',
                isFinish: false,
                steps: [],
            },
        ],
    },
    {
        userId: 3,
        userName: 'Jaxson Geidt',
        userIcon: '',
        position: 'qa',
        email: 'jaxson.geidt@gmail.com',
        phone: '+35795111111',
        skype: '@jaxson-geidt',
        link: 'https://www.linkedin.com/in/jaxson-geidt/',
        questionnaire: [
            {
                questId: 1,
                questName: 'questionnaire',
                startDate: '6.5.2022',
                endDate: '',
                status: 'open',
                isFinish: false,
                steps: [],
            },
        ],
    },
    {
        userId: 4,
        userName: 'Maren Westervelt',
        userIcon: '',
        position: 'developer',
        email: 'maren.westervelt@gmail.com',
        phone: '+35795111111',
        skype: '@maren-westervelt',
        link: 'https://www.linkedin.com/in/maren-westervelt/',
        questionnaire: [
            {
                questId: 1,
                questName: 'questionnaire',
                startDate: '7.5.2022',
                endDate: '',
                status: 'progress',
                isFinish: false,
                steps: [],
            },
        ],
    },
    {
        userId: 5,
        userName: 'Corey Dias',
        userIcon: '',
        position: 'qa',
        email: 'corey.dias@gmail.com',
        phone: '+35795111111',
        skype: '@corey-dias',
        link: 'https://www.linkedin.com/in/corey-dias/',
        questionnaire: [
            {
                questId: 1,
                questName: 'questionnaire',
                startDate: '5.5.2022',
                endDate: '',
                status: 'open',
                isFinish: false,
                steps: [],
            },
            {
                questId: 2,
                questName: 'contact information',
                startDate: '7.5.2022',
                endDate: '10.5.2022',
                status: 'done',
                isFinish: true,
                steps: [],
            },
        ],
    },
    {
        userId: 6,
        userName: 'Ryan Calzoni',
        userIcon: require('@/assets/users/default-user.png'),
        position: 'manager',
        email: 'ryan_calzoni@gmail.com',
        phone: '+35795111111',
        skype: '@ryan_calzoni',
        link: 'https://www.linkedin.com/in/ryan_calzoni/',
        questionnaire: [
            {
                questId: 1,
                questName: 'instruction',
                startDate: '5.5.2022',
                endDate: '6.5.2022',
                status: 'done',
                isFinish: true,
                steps: [],
            },
        ],
    },
];